name: Update the repo variable

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update the repo variable
      run: | 
        echo " Before update, value of the variable: "
        curl -L    -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/ghataSaxena/Testing-github-actions/actions/variables/QUALYSSCANID

        echo " Updating the value: to 5595861210"
        curl -L  -X PATCH  -H "Content-Type: application/json" -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/ghataSaxena/Testing-github-actions/actions/variables/QUALYSSCANID -d '{"name": "QUALYSSCANID","value": "5595861210"}' 
        
        echo " After update, value is"
        curl -L    -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/ghataSaxena/Testing-github-actions/actions/variables/QUALYSSCANID
        echo ${{ vars.QUALYSSCANID }}