name: Check status

on: 
  schedule:
    - cron: '2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch the variable and check status
      run: | 
        echo " value of the variable: "
        curl -L    -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/ghataSaxena/Testing-github-actions/actions/variables/QUALYSSCANID
